import citio from "../../../public/projects/citio.png";
import broccoli from "../../../public/projects/broccoli.png";
import medioApp from "../../../public/projects/medio.png";
import saka from "../../../public/projects/saka.jpeg";
import avis from "../../../public/projects/avis.jpeg";
import losbutik from "../../../public/projects/losbutik.jpeg";
import ora from "../../../public/projects/ora.png";
import roma from "../../../public/projects/roma.png";
import kidonki from "../../../public/projects/kidonki.png";
import panel from "../../../public/projects/panel.png";

export const projectDatas = [
  {
    projectName: "Citio",
    time: "1 Year",
    logo: "",
    image: citio,
    area: "Online Rezervasyon ve Satın Alma",
    tags: ["web", "e-commerce", "reservation", "online"],
    description:
      "Citio, müşterilere online rezervasyon ve satın alma hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Müşterilere kolay rezervasyon imkanı sağlamak",
      "Ürün ve hizmet satışlarını artırmak",
    ],
    scope:
      "Kullanıcı hesapları, rezervasyon işlemleri, ödeme sistemi, ürün yönetimi",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "Husky",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Zustand",
      "RTQ",
      "Linear",
      "Refine JS",
      "Restfull Api",
      "Context Provider",
      "Payment Gateway API",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Ürün yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
    ],
  },
  {
    projectName: "Medio App",
    time: "2 Years",
    logo: "",
    image: medioApp,
    area: "Yurtdışında Sağlık Turizmi",
    tags: ["web", "health", "medical tourism", "reservation", "online"],
    description:
      "Medio App, yurtdışında sağlık tedavilerini karşılamak amacıyla gelenlerin kullanabileceği online rezervasyon ve satın alma aracılık platformudur.",
    goals: [
      "Müşterilere yurtdışında sağlık tedavisi için kolay rezervasyon imkanı sağlamak",
      "Sağlık turizmini destekleyerek yerel sağlık hizmetlerine erişimi artırmak",
      "Güvenli ve etkili bir online satın alma platformu sunmak",
    ],
    scope:
      "Kullanıcı hesapları, sağlık rezervasyon işlemleri, ödeme sistemi, sağlık paket yönetimi",
    requirements: [
      "Next.js",
      "SCSS",
      "Jira",
      "Restfull Api",
      "Context Provider",
      "Payment Gateway API",
      "Socket IO",
      "Payment Gateway API",
      "Transfer Entregration",
      "Healthcare Provider Integration",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve sağlık rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Sağlık paket yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
    ],
  },
  {
    projectName: "Broccoli",
    time: "1 Year",
    logo: "",
    image: broccoli,
    area: "Online Diyet ve Sağlıklı Yaşam",
    tags: ["web", "health", "nutrition", "online"],
    description:
      "Broccoli, kullanıcılara online diyet ve sağlıklı yaşam hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Kullanıcılara kişiselleştirilmiş diyet programları sunmak",
      "Sağlıklı beslenme alışkanlıkları oluşturmak",
      "Kullanıcıların sağlıklı yaşam hedeflerine ulaşmalarını desteklemek",
    ],
    scope:
      "Kullanıcı hesapları, kişiselleştirilmiş diyet planları, besin takibi, ilerleme raporları",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "RTQ",
      "Tailwind",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Zustand",
      "Firabase",
      "Framer Motion",
      "Restfull Api",
      "Context Provider",
      "Payment Gateway API",
      "Nutrition API",
      "User Authentication System",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve kişiselleştirilmiş diyet planı geliştirme",
      "Besin takibi ve ilerleme raporları ekranı",
      "Ödeme sistemi entegrasyonu",
      "Beta sürüm çıkışı ve kullanıcı testleri",
    ],
  },

  {
    projectName: "Los Butik",
    time: "1 Year",
    logo: "",
    image: losbutik,
    area: "E-Ticaret",
    tags: ["web", "e-commerce", "online shopping"],
    description:
      "Los Butik, müşterilere online alışveriş ve e-ticaret hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Müşterilere kolay online alışveriş imkanı sağlamak",
      "Ürün ve hizmet satışlarını artırmak",
      "Güvenli ve kullanıcı dostu bir alışveriş deneyimi sunmak",
    ],
    scope:
      "Kullanıcı hesapları, ürün ve kategori yönetimi, ödeme sistemi, sipariş takibi",
    requirements: [
      "React Query",
      "Next.js",
      "SCSS",
      "Tailwind",
      "Git",
      "Linear",
      "Firabase",
      "Restfull Api",
      "Context Provider",
      "Payment Gateway API",
      "Iyzico",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve alışveriş ekranı geliştirme",
      "Ürün yönetimi ve satış ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Sipariş takip ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
    ],
  },

  {
    projectName: "Saka Soft",
    time: "1 Year",
    logo: "",
    image: saka,
    area: "Online Rezervasyon ve Satın Alma",
    tags: ["web", "reservation", "online booking", "customer service"],
    description:
      "Saka Soft, müşterilerin online rezervasyon ve satın alma taleplerini kolayca yönetmelerini sağlayan bir web uygulaması geliştirmeyi planlamaktadır.",
    goals: [
      "Müşterilere kolay rezervasyon ve satın alma imkanı sağlamak",
      "Şirket içi operasyonları daha etkili ve verimli hale getirmek",
      "Müşteri memnuniyetini artırmak",
    ],
    scope:
      "Müşteri hesapları, rezervasyon işlemleri, ödeme sistemi, ürün yönetimi",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "RTQ",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Tailwind",
      "Firabase",
      "Framer Motion",
      "Restfull Api",
      "Context Provider",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Müşteri hesapları ve rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Ürün yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
      "Müşteri destek ve geri bildirim sistemi oluşturma",
    ],
  },
  {
    projectName: "Roma Solution",
    time: "1 Year",
    logo: "",
    image: roma,
    area: "Online İş Talepleri ve Proje Yönetimi",
    tags: ["web", "project management", "international", "online"],
    description:
      "Roma Solution, yurt dışından gelen iş taleplerini almayı ve projeleri etkili bir şekilde yönetmeyi amaçlayan bir web uygulamasıdır.",
    goals: [
      "Yurt dışındaki müşterilerden iş taleplerini kolayca almak",
      "Projeleri etkili bir şekilde planlamak ve yönetmek",
      "İşbirliği ve iletişimi artırmak",
    ],
    scope:
      "Müşteri talepleri, proje yönetimi, işbirliği platformu, iletişim araçları",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "RTQ",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Tailwind",
      "Firabase",
      "Framer Motion",
      "Restfull Api",
      "Context Provider",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Internationalization Support",
      "Collaboration Tools",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Müşteri talepleri ve proje ekranı geliştirme",
      "İşbirliği ve iletişim araçları entegrasyonu",
      "Proje yönetimi araçları oluşturma",
      "Beta sürüm çıkışı ve testler",
    ],
  },

  {
    projectName: "Avis Agri",
    time: "1 Year",
    logo: "",
    image: avis,
    area: "Online Zirai Drone Satışı",
    tags: ["web", "e-commerce", "agriculture", "drone", "online"],
    description:
      "Avis Agri, müşterilere online zirai drone satışı ve rezervasyon hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Müşterilere kolay zirai drone satın alma imkanı sağlamak",
      "Zirai drone teknolojisinin kullanımını artırmak",
      "Müşterilere özel uçuş ve rezervasyon seçenekleri sunmak",
    ],
    scope:
      "Kullanıcı hesapları, ürün rezervasyon işlemleri, ödeme sistemi, zirai drone yönetimi",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "RTQ",
      "Husky",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Tailwind",
      "Firabase",
      "Framer Motion",
      "Restfull Api",
      "Context Provider",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Payment Gateway API",
      "Drone Management System",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve zirai drone rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Zirai drone yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
    ],
  },
  {
    projectName: "Ora",
    time: "1 Year",
    logo: "",
    image: ora,
    area: "Online Zirai Drone Satışı",
    tags: ["web", "e-commerce", "agriculture", "drone", "online"],
    description:
      "Avis Agri, müşterilere online zirai drone satışı ve rezervasyon hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Müşterilere kolay zirai drone satın alma imkanı sağlamak",
      "Zirai drone teknolojisinin kullanımını artırmak",
      "Müşterilere özel uçuş ve rezervasyon seçenekleri sunmak",
    ],
    scope:
      "Kullanıcı hesapları, ürün rezervasyon işlemleri, ödeme sistemi, zirai drone yönetimi",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "RTQ",
      "Firabase",
      "Framer Motion",
      "Restfull Api",
      "Context Provider",
      "Commitlint",
      "Lint Stage",
      "Prettier",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve zirai drone rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Zirai drone yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
    ],
  },
  {
    projectName: "CMS Panel",
    time: "1 Year",
    logo: "",
    image: panel,
    area: "Online Zirai Drone Satışı",
    tags: ["web", "e-commerce", "agriculture", "drone", "online"],
    description:
      "Avis Agri, müşterilere online zirai drone satışı ve rezervasyon hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Müşterilere kolay zirai drone satın alma imkanı sağlamak",
      "Zirai drone teknolojisinin kullanımını artırmak",
      "Müşterilere özel uçuş ve rezervasyon seçenekleri sunmak",
    ],
    scope:
      "Kullanıcı hesapları, ürün rezervasyon işlemleri, ödeme sistemi, zirai drone yönetimi",
    requirements: [
      "React.js",
      "Node.js",
      "MongoDB",
      "Express.js",
      "Payment Gateway API",
      "Drone Management System",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve zirai drone rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Zirai drone yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
    ],
  },
  {
    projectName: "Kidonki",
    time: "1 Year",
    logo: "",
    image: kidonki,
    area: "Online Zirai Drone Satışı",
    tags: ["web", "e-commerce", "agriculture", "drone", "online"],
    description:
      "Avis Agri, müşterilere online zirai drone satışı ve rezervasyon hizmetleri sunan bir web uygulamasıdır.",
    goals: [
      "Müşterilere kolay zirai drone satın alma imkanı sağlamak",
      "Zirai drone teknolojisinin kullanımını artırmak",
      "Müşterilere özel uçuş ve rezervasyon seçenekleri sunmak",
    ],
    scope:
      "Kullanıcı hesapları, ürün rezervasyon işlemleri, ödeme sistemi, zirai drone yönetimi",
    requirements: [
      "Next.js",
      "SCSS",
      "Git",
      "RTQ",
      "Husky",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Tailwind",
      "Firabase",
      "Framer Motion",
      "Restfull Api",
      "Context Provider",
      "Commitlint",
      "Lint Stage",
      "Prettier",
      "Payment Gateway API",
      "Drone Management System",
    ],
    tasks: [
      "Temel altyapı oluşturma",
      "Kullanıcı hesapları ve zirai drone rezervasyon ekranı geliştirme",
      "Ödeme sistemi entegrasyonu",
      "Zirai drone yönetimi ve satış ekranı geliştirme",
      "Beta sürüm çıkışı ve testler",
      "Resmi lansman",
    ],
  },
];
